name: salka_pos
description: KasirKu SalKa - Aplikasi Kasir POS Android dengan Printer Thermal Bluetooth
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  flutter_blue_plus: ^1.35.2
  esc_pos_utils_plus: ^2.0.4
  permission_handler: ^11.3.1
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
